# global CS origin
# applies only to 'camera_pose_marker'
root:
  rpy: [0, 0, 0]
  xyz: [0, 0, 0]

# camera pose estimation result
# if not null, the camera pose estimation step is skipped
# assuming the correct camera pose wrt. root is present
camera_pose:
  xyz: null
  rpy: null

# marker transformations wrt. root for the camera pose detection
# required if camera_pose is null
camera_pose_marker:
  0:
    rpy: &euler [0, 0, 0]
    xyz: [0.520, 0, 0.240]

  1:
    rpy: *euler
    xyz: [0.550, 0.030, 0.340]

  2:
    rpy: *euler
    xyz: [0.550, -0.030, 0.340]

# marker transformation results wrt. root using the known camera pose 
# the entries are used to transform the marker pose results into a target frame
# if an entry is null, only the marker transformation will be estimated
# the 'root' transformation is not applicable here, use absolute values
target-1_marker:
  10:
    rpy: &euler_target1 [0, 0, 0]
    xyz: [0, 0, 0]

  11:
    rpy: *euler_target1
    xyz: [0, 0, 0]

# 2nd target
target-2_marker:
  20:
    rpy: &euler_target2 [0, 0, 0]
    xyz: [0, 0, 0]

  21:
    rpy: *euler_target2
    xyz: [0, 0, 0]
